# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52112871d6c3bb2f6462f434cd594d713e87a7ca7da2da04f6e10faffa0c7e6de0672e5d04f3f768faa67c9704da926a7910310f00000e60619954b200c1fe84

test:
  secret_key_base: 27a8b26b3c10acccc385e4e246c1af1750a682324f1c7c5f6e8fd7975de6e0b9cdae08e236dd177e03902dd36b1e532cb8548df5b8659ff02a886eeda7d388a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
